import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAlerts } from '../components/AlertProvider';
import { notaryProcessesApi } from '../services/notaryProcesses';

const today = new Date().toISOString().slice(0, 10); const currentMonth = today.slice(0, 7);
export function NotaryCalendarPage() {
  const [month, setMonth] = useState(currentMonth); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const { notify } = useAlerts();
  const load = async () => { setLoading(true); const [year, value] = month.split('-').map(Number); const from = `${month}-01`; const to = new Date(year, value, 0).toISOString().slice(0, 10); try { setItems(await notaryProcessesApi.calendar(from, to)); } catch (error) { notify('error', 'No se pudo cargar el calendario', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [month]);
  const stats = useMemo(() => ({ overdue: items.filter((item) => item.fecha_limite < today && item.estatus !== 'completado').length, pending: items.filter((item) => !['completado','cancelado'].includes(item.estatus)).length, done: items.filter((item) => item.estatus === 'completado').length }), [items]);
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Control de vencimientos</p><h1 className="mt-1 text-3xl font-bold">Calendario notarial</h1><p className="mt-2 text-sm text-slate-500">Prioriza etapas críticas y evita que un plazo pase inadvertido.</p></div><input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="h-11 rounded-xl border bg-white px-4 text-sm font-bold"/></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card icon={AlertTriangle} label="Vencidas" value={stats.overdue} color="red"/><Card icon={Clock3} label="Pendientes del mes" value={stats.pending} color="amber"/><Card icon={CheckCircle2} label="Completadas" value={stats.done} color="green"/></div>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-2"><CalendarDays className="h-5 w-5 text-blue-600"/><h2 className="text-lg font-bold">Agenda del mes</h2></div>{loading ? <p className="py-10 text-center text-sm text-slate-500">Cargando agenda...</p> : items.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">No hay vencimientos programados para este mes.</p> : <div className="space-y-3">{items.map((item) => { const overdue = item.fecha_limite < today && item.estatus !== 'completado'; const client = item.notaria_expedientes?.notaria_clientes; const name = [client?.nombres, client?.apellido_paterno, client?.apellido_materno].filter(Boolean).join(' '); return <Link key={item.id} to={`/notaria/expedientes/${item.notaria_expedientes?.id}`} className={`grid gap-3 rounded-xl border p-4 transition hover:shadow-sm md:grid-cols-[90px_1fr_160px] md:items-center ${overdue ? 'border-red-200 bg-red-50/50' : item.estatus === 'completado' ? 'border-emerald-200 bg-emerald-50/40' : ''}`}><div><p className={`text-lg font-bold ${overdue ? 'text-red-600' : 'text-slate-800'}`}>{item.fecha_limite.slice(8, 10)}</p><p className="text-xs uppercase text-slate-400">{new Date(`${item.fecha_limite}T12:00:00`).toLocaleDateString('es-MX', { weekday: 'short' })}</p></div><div><div className="flex flex-wrap gap-2"><span className="font-mono text-xs font-bold text-blue-600">{item.notaria_expedientes?.folio}</span>{overdue && <span className="rounded-full bg-red-100 px-2 py-0.5 text-[10px] font-bold uppercase text-red-700">Vencida</span>}</div><h3 className="mt-1 font-bold">{item.concepto}</h3><p className="mt-1 text-sm text-slate-500">{item.notaria_expedientes?.titulo} · {name}</p></div><div className="md:text-right"><p className="text-xs text-slate-400">Estatus</p><p className="mt-1 text-sm font-bold capitalize">{item.estatus.replace('_', ' ')}</p></div></Link>; })}</div>}</section>
  </div>;
}
function Card({ icon: Icon, label, value, color }: any) { const styles: any = { red: 'bg-red-50 text-red-600', amber: 'bg-amber-50 text-amber-600', green: 'bg-emerald-50 text-emerald-600' }; return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className={`rounded-xl p-2.5 ${styles[color]}`}><Icon className="h-5 w-5"/></span><div><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-bold">{value}</p></div></div></div>; }
