import { useState, type MouseEvent, type ReactNode } from 'react';
import { ArrowLeft, Download, FileText, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Input } from '../components/Input';
import { useAlerts } from '../components/AlertProvider';
import { buildNotarySearchOfficeText, downloadBlob } from '../lib/notaryDocuments';
import { notaryDocumentsApi } from '../services/notaryDocuments';
import type { NotarySearchOfficeData, NotaryStoredDocument } from '../types/notary';

const today = new Date().toISOString().slice(0, 10);
const initialData: NotarySearchOfficeData = {
  place: 'La Paz, B.C.S.', issueDate: today,
  authorityName: 'LIC. SONIA GUADALUPE CORRAL DOMÍNGUEZ', authorityTitle: 'DIRECTORA DEL ARCHIVO GENERAL DE NOTARÍAS', authorityDepartment: 'DEL ESTADO DE BAJA CALIFORNIA SUR', authorityGender: 'F',
  radicationInstrument: '', radicationVolume: '', radicationDate: '', deceasedName: '', deceasedGender: 'M',
  willInstrument: '', willVolume: '', willNotaryName: '', willNotaryNumber: '', willPlace: 'La Paz, Baja California Sur', willDate: '',
  nationality: 'mexicano', birthCity: '', birthState: '', birthDate: '', maritalStatus: '', occupation: '',
  street: '', exteriorNumber: '', interiorNumber: '', neighborhood: '', postalCode: '', city: 'La Paz', state: 'Baja California Sur',
  curp: '', rfc: '', ineFolio: '', fatherName: '', fatherDeceased: true, motherName: '', motherDeceased: true,
  signerName: 'LIC. ALEJANDRO DAVIS MONZÓN', signerTitle: 'NOTARIO PÚBLICO No. DOS', legalBasis: 'lo dispuesto por el artículo 750 del Código de Procedimientos Civiles vigente en la entidad',
};

export function NotarySearchOfficePage() {
  const [data, setData] = useState(initialData); const [preview, setPreview] = useState(false); const [saving, setSaving] = useState(false); const [savedDocument, setSavedDocument] = useState<NotaryStoredDocument | null>(null); const [savedSnapshot, setSavedSnapshot] = useState(''); const { notify } = useAlerts();
  const set = <K extends keyof NotarySearchOfficeData>(key: K, value: NotarySearchOfficeData[K]) => setData((current) => ({ ...current, [key]: value }));
  const submit = async (event: MouseEvent<HTMLButtonElement>, type: 'word' | 'pdf') => { event.preventDefault(); if (!event.currentTarget.form?.reportValidity()) return; setSaving(true); try { const snapshot = JSON.stringify(data); const record = savedDocument && snapshot === savedSnapshot ? savedDocument : await notaryDocumentsApi.createSearchOffice(data); if (record !== savedDocument) { setSavedDocument(record); setSavedSnapshot(snapshot); } const blob = await notaryDocumentsApi.download(record, type); downloadBlob(blob, `${record.folio}-${data.deceasedName.replace(/\s+/g, '-').toLowerCase()}.${type === 'word' ? 'docx' : 'pdf'}`); notify('success', `Documento guardado · ${record.folio}`, `El oficio quedó archivado y la descarga en ${type === 'word' ? 'Word' : 'PDF'} comenzó.`); } catch (error) { notify('error', 'No se pudo guardar el oficio', error instanceof Error ? error.message : 'Revisa los datos e intenta nuevamente.'); } finally { setSaving(false); } };
  return <form className="space-y-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Link to="/notaria" className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:text-blue-700"><ArrowLeft className="h-4 w-4"/> Volver a formatos</Link><h1 className="text-3xl font-bold tracking-tight">Búsqueda de radicación</h1><p className="mt-2 text-sm text-slate-500">Genera el oficio para solicitar información sobre disposiciones testamentarias posteriores.</p>{savedDocument ? <p className="mt-2 text-sm font-bold text-emerald-700">Guardado con folio {savedDocument.folio}</p> : null}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setPreview((value) => !value)} className="inline-flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100"><FileText className="h-4 w-4"/>{preview ? 'Ocultar vista previa' : 'Vista previa'}</button><button type="button" disabled={saving} onClick={(event) => void submit(event, 'pdf')} className="inline-flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100 disabled:opacity-50"><Download className="h-4 w-4"/>{saving ? 'Guardando...' : 'Guardar y descargar PDF'}</button><button type="button" disabled={saving} onClick={(event) => void submit(event, 'word')} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 disabled:opacity-50"><Download className="h-4 w-4"/>{saving ? 'Guardando...' : 'Guardar y descargar Word'}</button></div></div>
    <div className="flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/><p>La información permanece en este navegador. Revisa nombres, fechas y fundamento legal antes de firmar.</p></div>
    <FormSection title="Autoridad y oficio" description="Puedes sustituir los datos para generar el mismo formato dirigido a la segunda autoridad."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Input required label="Lugar de expedición" value={data.place} onChange={(e) => set('place', e.target.value)}/><Input required type="date" label="Fecha del oficio" value={data.issueDate} onChange={(e) => set('issueDate', e.target.value)}/><SelectField label="Tratamiento de la autoridad" value={data.authorityGender} onChange={(value) => set('authorityGender', value as 'M'|'F')} options={[['F','Femenino'],['M','Masculino']]}/><Input required label="Nombre de la autoridad" value={data.authorityName} onChange={(e) => set('authorityName', e.target.value.toUpperCase())}/><Input required label="Cargo" value={data.authorityTitle} onChange={(e) => set('authorityTitle', e.target.value.toUpperCase())}/><Input required label="Dependencia" value={data.authorityDepartment} onChange={(e) => set('authorityDepartment', e.target.value.toUpperCase())}/></div></FormSection>
    <FormSection title="Radicación de la sucesión"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Input required label="Instrumento de radicación" value={data.radicationInstrument} onChange={(e) => set('radicationInstrument', e.target.value)}/><Input required label="Volumen" value={data.radicationVolume} onChange={(e) => set('radicationVolume', e.target.value)}/><Input required type="date" label="Fecha de radicación" value={data.radicationDate} onChange={(e) => set('radicationDate', e.target.value)}/><SelectField label="Sexo de la persona fallecida" value={data.deceasedGender} onChange={(value) => set('deceasedGender', value as 'M'|'F')} options={[['M','Masculino'],['F','Femenino']]}/><Input required label="Nombre completo" containerClassName="md:col-span-2" value={data.deceasedName} onChange={(e) => set('deceasedName', e.target.value.toUpperCase())}/></div></FormSection>
    <FormSection title="Testamento utilizado"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Input required label="Instrumento del testamento" value={data.willInstrument} onChange={(e) => set('willInstrument', e.target.value)}/><Input required label="Volumen" value={data.willVolume} onChange={(e) => set('willVolume', e.target.value)}/><Input required label="Nombre del notario" value={data.willNotaryName} onChange={(e) => set('willNotaryName', e.target.value.toUpperCase())}/><Input required label="Número de notaría" value={data.willNotaryNumber} onChange={(e) => set('willNotaryNumber', e.target.value)}/><Input required label="Lugar de otorgamiento" containerClassName="md:col-span-2" value={data.willPlace} onChange={(e) => set('willPlace', e.target.value)}/><Input required type="date" label="Fecha del testamento" value={data.willDate} onChange={(e) => set('willDate', e.target.value)}/></div></FormSection>
    <FormSection title="Datos personales"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Input required label="Nacionalidad" value={data.nationality} onChange={(e) => set('nationality', e.target.value.toLowerCase())}/><Input required label="Ciudad de nacimiento" value={data.birthCity} onChange={(e) => set('birthCity', e.target.value)}/><Input required label="Estado de nacimiento" value={data.birthState} onChange={(e) => set('birthState', e.target.value)}/><Input required type="date" label="Fecha de nacimiento" value={data.birthDate} onChange={(e) => set('birthDate', e.target.value)}/><Input required label="Estado civil" value={data.maritalStatus} onChange={(e) => set('maritalStatus', e.target.value.toLowerCase())}/><Input label="Ocupación" value={data.occupation} onChange={(e) => set('occupation', e.target.value)}/><Input required label="CURP" maxLength={18} value={data.curp} onChange={(e) => set('curp', e.target.value.toUpperCase())}/><Input required label="RFC" maxLength={13} value={data.rfc} onChange={(e) => set('rfc', e.target.value.toUpperCase())}/><Input required label="Folio INE" value={data.ineFolio} onChange={(e) => set('ineFolio', e.target.value.toUpperCase())}/></div></FormSection>
    <FormSection title="Domicilio"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Input required label="Calle" value={data.street} onChange={(e) => set('street', e.target.value)}/><Input required label="Número exterior" value={data.exteriorNumber} onChange={(e) => set('exteriorNumber', e.target.value)}/><Input label="Número interior" value={data.interiorNumber} onChange={(e) => set('interiorNumber', e.target.value)}/><Input label="Colonia o fraccionamiento" value={data.neighborhood} onChange={(e) => set('neighborhood', e.target.value)}/><Input label="Código postal" maxLength={5} value={data.postalCode} onChange={(e) => set('postalCode', e.target.value.replace(/\D/g,''))}/><Input required label="Ciudad" value={data.city} onChange={(e) => set('city', e.target.value)}/><Input required label="Estado" value={data.state} onChange={(e) => set('state', e.target.value)}/></div></FormSection>
    <FormSection title="Padres"><div className="grid gap-4 md:grid-cols-2"><ParentField label="Nombre del padre" name={data.fatherName} deceased={data.fatherDeceased} onName={(value) => set('fatherName', value)} onStatus={(value) => set('fatherDeceased', value)}/><ParentField label="Nombre de la madre" name={data.motherName} deceased={data.motherDeceased} onName={(value) => set('motherName', value)} onStatus={(value) => set('motherDeceased', value)}/></div></FormSection>
    <FormSection title="Fundamento y firma"><div className="grid gap-4 md:grid-cols-2"><Input required label="Fundamento legal" containerClassName="md:col-span-2" value={data.legalBasis} onChange={(e) => set('legalBasis', e.target.value)}/><Input required label="Nombre del firmante" value={data.signerName} onChange={(e) => set('signerName', e.target.value.toUpperCase())}/><Input required label="Cargo del firmante" value={data.signerTitle} onChange={(e) => set('signerTitle', e.target.value.toUpperCase())}/></div></FormSection>
    {preview ? <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Vista previa del texto</h2><p className="mt-4 whitespace-pre-wrap text-justify font-serif leading-8 text-slate-700">{buildNotarySearchOfficeText(data)}</p></section> : null}
  </form>;
}

function FormSection({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5"><h2 className="text-lg font-bold">{title}</h2>{description ? <p className="mt-1 text-sm text-slate-500">{description}</p> : null}</div>{children}</section>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: [string,string][]; onChange: (value: string) => void }) { return <label className="flex w-full flex-col gap-1.5 text-sm font-medium text-slate-700">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-md border bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-indigo-500">{options.map(([key,text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function ParentField({ label, name, deceased, onName, onStatus }: { label: string; name: string; deceased: boolean; onName: (value: string) => void; onStatus: (value: boolean) => void }) { return <div className="space-y-3 rounded-xl border bg-slate-50 p-4"><Input required label={label} value={name} onChange={(e) => onName(e.target.value.toUpperCase())}/><label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={deceased} onChange={(e) => onStatus(e.target.checked)} className="h-4 w-4 rounded accent-blue-600"/> Persona fallecida</label></div>; }
