import { useState, type FormEvent } from 'react';
import { Eye, EyeOff, KeyRound, ShieldCheck, UserRound } from 'lucide-react';
import { Input } from '../components/Input';
import { useAlerts } from '../components/AlertProvider';
import { notaryUserApi } from '../services/notaryUser';

export function NotaryUserPage() {
  const [name, setName] = useState('Vladimir Davis'); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [show, setShow] = useState(false); const [saving, setSaving] = useState(false); const { notify } = useAlerts();
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password !== confirmation) { notify('warning', 'Las contraseñas no coinciden', 'Escribe la misma contraseña en ambos campos.'); return; } setSaving(true); try { const result = await notaryUserApi.savePassword({ name, password }); notify('success', result.created ? 'Usuario creado' : 'Contraseña actualizada', 'vladimir_davis ya puede ingresar únicamente al módulo Notaría.'); setPassword(''); setConfirmation(''); } catch (error) { notify('error', 'No se pudo guardar el usuario', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-2xl space-y-6"><div><h1 className="text-3xl font-bold tracking-tight">Usuario de Notaría</h1><p className="mt-2 text-sm text-slate-500">Crea la cuenta exclusiva del módulo o reemplaza su contraseña.</p></div><div className="flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/><p>La contraseña se envía directamente a Supabase Auth. El sistema no la guarda ni permite consultarla posteriormente.</p></div><form onSubmit={submit} className="space-y-5 rounded-2xl border bg-white p-6 shadow-sm"><label className="block text-sm font-medium text-slate-700">Nombre de usuario<div className="relative mt-2"><UserRound className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input readOnly value="vladimir_davis" className="h-11 w-full rounded-xl border bg-slate-100 pl-10 pr-4 font-mono text-sm text-slate-600"/></div></label><Input required label="Nombre visible" value={name} onChange={(event) => setName(event.target.value)}/><PasswordField label="Contraseña nueva" value={password} show={show} onChange={setPassword}/><PasswordField label="Confirmar contraseña" value={confirmation} show={show} onChange={setConfirmation}/><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={show} onChange={(event) => setShow(event.target.checked)} className="h-4 w-4 accent-blue-600"/>{show ? <EyeOff className="h-4 w-4"/> : <Eye className="h-4 w-4"/>} Mostrar contraseña</label><button disabled={saving} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 font-bold text-white hover:bg-blue-700 disabled:opacity-50"><KeyRound className="h-4 w-4"/>{saving ? 'Guardando...' : 'Crear usuario o cambiar contraseña'}</button></form></div>;
}

function PasswordField({ label, value, show, onChange }: { label: string; value: string; show: boolean; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-slate-700">{label}<span className="text-red-500"> *</span><input required minLength={8} autoComplete="new-password" type={show ? 'text' : 'password'} value={value} onChange={(event) => onChange(event.target.value)} placeholder="Mínimo 8 caracteres" className="mt-2 h-11 w-full rounded-xl border px-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"/></label>; }
