import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarClock, CircleDollarSign, FilePlus2, FolderKanban, Search, UserRound, UsersRound } from 'lucide-react';
import { notaryProcessesApi } from '../services/notaryProcesses';
import type { NotaryCase } from '../types/notaryProcess';
import { useAlerts } from '../components/AlertProvider';

const money = (value: number) => value.toLocaleString('es-MX', { style: 'currency', currency: 'MXN' });
const badge: Record<string, string> = { activo: 'bg-blue-50 text-blue-700', borrador: 'bg-slate-100 text-slate-600', pausado: 'bg-amber-50 text-amber-700', concluido: 'bg-emerald-50 text-emerald-700', cancelado: 'bg-red-50 text-red-700' };
export function NotaryCasesPage() {
  const [items, setItems] = useState<NotaryCase[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const { notify } = useAlerts();
  const load = async () => { setLoading(true); try { setItems(await notaryProcessesApi.listCases(query)); } catch (error) { notify('error', 'No se pudieron cargar los expedientes', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const totals = useMemo(() => ({ active: items.filter((item) => item.status === 'activo').length, value: items.reduce((sum, item) => sum + (item.generalCost || item.stages.reduce((value, stage) => value + stage.cost, 0)) - item.discount, 0) }), [items]);
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Notaría 2</p><h1 className="mt-1 text-3xl font-bold">Expedientes notariales</h1><p className="mt-2 text-sm text-slate-500">Control integral de clientes, trámites, documentos, costos y pagos.</p></div><div className="flex flex-wrap gap-2"><Link to="/notaria/sucesiones" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold text-slate-700 hover:bg-slate-50"><UsersRound className="h-4 w-4"/>Sucesiones</Link><Link to="/notaria/expedientes/nuevo" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white shadow-sm hover:bg-blue-700"><FilePlus2 className="h-4 w-4"/>Nuevo expediente</Link></div></div>
    <div className="grid gap-4 sm:grid-cols-3"><Stat icon={FolderKanban} label="Expedientes visibles" value={String(items.length)}/><Stat icon={CalendarClock} label="Activos" value={String(totals.active)}/><Stat icon={CircleDollarSign} label="Valor cotizado" value={money(totals.value)}/></div>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void load()} placeholder="Buscar por folio o nombre del expediente" className="h-10 w-full rounded-xl border pl-10 pr-4 text-sm outline-none focus:border-blue-500"/></div><button onClick={() => void load()} className="rounded-xl border px-5 text-sm font-bold text-slate-700 hover:bg-slate-50">Buscar</button></div>
      {loading ? <p className="p-8 text-center text-sm text-slate-500">Cargando expedientes...</p> : items.length === 0 ? <div className="p-12 text-center"><FolderKanban className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-3 font-bold">Aún no hay expedientes</p><p className="mt-1 text-sm text-slate-500">Crea el primero para comenzar el seguimiento.</p></div> : <div className="divide-y">{items.map((item) => <Link key={item.id} to={`/notaria/expedientes/${item.id}`} className="grid gap-3 p-5 transition hover:bg-slate-50 md:grid-cols-[1fr_180px_150px] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-bold text-blue-600">{item.folio}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${badge[item.status]}`}>{item.status}</span></div><h2 className="mt-2 font-bold text-slate-900">{item.title}</h2><p className="mt-1 flex items-center gap-1.5 text-sm text-slate-500"><UserRound className="h-3.5 w-3.5"/>{notaryProcessesApi.clientName(item.client)} · {item.client.curp}</p></div><div><p className="text-xs text-slate-400">Operación</p><p className="mt-1 text-sm font-semibold">{item.operationType}</p></div><div className="md:text-right"><p className="text-xs text-slate-400">Fecha objetivo</p><p className="mt-1 text-sm font-semibold">{item.targetDate || 'Por definir'}</p></div></Link>)}</div>}
    </section>
  </div>;
}
function Stat({ icon: Icon, label, value }: { icon: any; label: string; value: string }) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><Icon className="h-5 w-5"/></span><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-0.5 text-xl font-bold">{value}</p></div></div></div>; }
