import { useEffect, useMemo, useState } from 'react';
import { Download, FileText, Search } from 'lucide-react';
import { Input } from '../components/Input';
import { useAlerts } from '../components/AlertProvider';
import { notaryDocumentsApi } from '../services/notaryDocuments';
import type { NotaryStoredDocument } from '../types/notary';

const formatNames: Record<string, string> = { BUSQUEDA_RADICACION: 'Búsqueda de radicación' };
export function NotaryDocumentsPage() {
  const [documents, setDocuments] = useState<NotaryStoredDocument[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const { notify } = useAlerts();
  useEffect(() => { let active = true; notaryDocumentsApi.list().then((rows) => { if (active) setDocuments(rows); }).catch((error) => notify('error', 'No se pudo cargar el archivo notarial', error.message)).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [notify]);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); if (!needle) return documents; return documents.filter((item) => `${item.folio} ${item.referenceName} ${formatNames[item.formatType] || item.formatType} ${item.authority} ${item.createdAt}`.toLowerCase().includes(needle)); }, [documents, query]);
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight">Archivo de documentos</h1><p className="mt-2 text-sm text-slate-500">Consulta y descarga los oficios generados desde el módulo Notaría.</p></div><div className="relative"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><Input className="h-11 pl-10" placeholder="Buscar por folio, nombre, formato o autoridad..." value={query} onChange={(event) => setQuery(event.target.value)}/></div><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[950px] w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs font-bold uppercase text-slate-500"><tr><th className="px-5 py-4">Folio</th><th className="px-5 py-4">Nombre</th><th className="px-5 py-4">Formato</th><th className="px-5 py-4">Autoridad</th><th className="px-5 py-4">Fecha</th><th className="px-5 py-4 text-right">Archivos</th></tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-400">Cargando documentos...</td></tr> : filtered.length ? filtered.map((item) => <tr key={item.id} className="hover:bg-blue-50/40"><td className="px-5 py-4 font-mono font-bold text-blue-700">{item.folio}</td><td className="px-5 py-4 font-semibold">{item.referenceName}</td><td className="px-5 py-4">{formatNames[item.formatType] || item.formatType}</td><td className="max-w-72 px-5 py-4 text-slate-600">{item.authority}</td><td className="whitespace-nowrap px-5 py-4">{new Date(item.createdAt).toLocaleString('es-MX')}</td><td className="px-5 py-4"><div className="flex justify-end gap-2">{item.docxUrl ? <a href={item.docxUrl} download className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 font-medium hover:bg-slate-50"><FileText className="h-4 w-4"/>Word</a> : null}{item.pdfUrl ? <a href={item.pdfUrl} download className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-3 py-2 font-medium text-white hover:bg-blue-700"><Download className="h-4 w-4"/>PDF</a> : null}</div></td></tr>) : <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-400">No se encontraron documentos.</td></tr>}</tbody></table></div></section></div>;
}
