import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarClock, CheckCircle2, Download, FileText, Landmark, LockKeyhole, Upload, WalletCards } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useAlerts } from '../components/AlertProvider';
import { Input } from '../components/Input';
import { downloadNotaryQuote, downloadPaymentOrder } from '../lib/notaryProcessDocuments';
import { notaryProcessesApi } from '../services/notaryProcesses';
import type { NotaryCase, NotaryStageStatus } from '../types/notaryProcess';

const today = new Date().toISOString().slice(0, 10); const money = (value: number) => value.toLocaleString('es-MX', { style: 'currency', currency: 'MXN' });
const inputClass = 'h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm outline-none focus:border-blue-500';
export function NotaryCaseDetailPage() {
  const { id = '' } = useParams(); const [item, setItem] = useState<NotaryCase | null>(null); const [loading, setLoading] = useState(true); const [payment, setPayment] = useState({ date: today, amount: 0, method: 'Transferencia', reference: '', notes: '' }); const [order, setOrder] = useState({ concept: 'Anticipo de servicios notariales', amount: 0, deadline: '' }); const [doc, setDoc] = useState({ type: 'INE', expiresAt: '', notes: '', file: null as File | null }); const [saving, setSaving] = useState(''); const { notify } = useAlerts();
  const load = async () => { try { setItem(await notaryProcessesApi.getCase(id)); } catch (error) { notify('error', 'No se pudo cargar el expediente', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [id]);
  const totals = useMemo(() => { if (!item) return { total: 0, paid: 0, pending: 0 }; const subtotal = item.generalCost || item.stages.reduce((sum, stage) => sum + stage.cost, 0); const total = Math.max(0, subtotal - item.discount); const paid = item.payments.reduce((sum, value) => sum + value.amount, 0); return { total, paid, pending: Math.max(0, total - paid) }; }, [item]);
  const updateStage = async (index: number, status: NotaryStageStatus) => { if (!item) return; const previousPending = item.stages.slice(0, index).some((stage) => !['completado', 'cancelado'].includes(stage.status)); if (status === 'completado' && previousPending) return notify('warning', 'Etapa bloqueada', 'Concluye o cancela las etapas anteriores antes de cerrar ésta.'); setSaving(`stage-${index}`); try { await notaryProcessesApi.updateStage(item.stages[index].id, status); await load(); notify('success', 'Etapa actualizada'); } catch (error) { notify('error', 'No se pudo actualizar', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setSaving(''); } };
  const addPayment = async (event: FormEvent) => { event.preventDefault(); if (payment.amount <= 0 || payment.amount > totals.pending) return notify('warning', 'Importe inválido', `El abono debe ser mayor a cero y no superar ${money(totals.pending)}.`); setSaving('payment'); try { await notaryProcessesApi.addPayment(id, payment); setPayment({ date: today, amount: 0, method: 'Transferencia', reference: '', notes: '' }); await load(); notify('success', 'Pago registrado', 'El saldo se actualizó correctamente.'); } catch (error) { notify('error', 'No se pudo registrar el pago', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setSaving(''); } };
  const createOrder = async (event: FormEvent) => { event.preventDefault(); if (!item || order.amount <= 0 || order.amount > totals.pending) return notify('warning', 'Importe inválido', 'La orden no puede superar el saldo pendiente.'); setSaving('order'); try { const saved = await notaryProcessesApi.createPaymentOrder(id, order); downloadPaymentOrder(item, saved); setOrder({ concept: 'Anticipo de servicios notariales', amount: 0, deadline: '' }); await load(); notify('success', 'Orden de pago creada', `Folio ${saved.folio}.`); } catch (error) { notify('error', 'No se pudo crear la orden', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setSaving(''); } };
  const upload = async (event: FormEvent) => { event.preventDefault(); if (!item || !doc.file) return; setSaving('document'); try { await notaryProcessesApi.uploadClientDocument(item.client.id, { ...doc, file: doc.file }); setDoc({ type: 'INE', expiresAt: '', notes: '', file: null }); await load(); notify('success', 'Documento guardado'); } catch (error) { notify('error', 'No se pudo subir el documento', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setSaving(''); } };
  const downloadDoc = async (path: string, name: string) => { try { const blob = await notaryProcessesApi.downloadClientDocument(path); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); } catch (error) { notify('error', 'No se pudo descargar', error instanceof Error ? error.message : 'Intenta nuevamente.'); } };
  if (loading) return <p className="py-12 text-center text-sm text-slate-500">Cargando expediente...</p>; if (!item) return <p>Expediente no encontrado.</p>;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Link to="/notaria/expedientes" className="inline-flex items-center gap-2 text-sm font-bold text-blue-600"><ArrowLeft className="h-4 w-4"/>Expedientes</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold">{item.title}</h1><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold uppercase text-blue-700">{item.status}</span></div><p className="mt-2 font-mono text-sm font-bold text-slate-500">{item.folio}</p></div><button onClick={() => downloadNotaryQuote(item)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-900 px-5 text-sm font-bold text-white"><Download className="h-4 w-4"/>Descargar cotización</button></div>
    <div className="grid gap-4 md:grid-cols-3"><Summary label="Total cotizado" value={money(totals.total)} icon={WalletCards}/><Summary label="Pagado" value={money(totals.paid)} icon={CheckCircle2} green/><Summary label="Saldo pendiente" value={money(totals.pending)} icon={Landmark} danger={totals.pending > 0}/></div>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Cliente</h2><div className="mt-4 grid gap-4 text-sm md:grid-cols-3"><Info label="Nombre" value={notaryProcessesApi.clientName(item.client)}/><Info label="CURP" value={item.client.curp}/><Info label="RFC" value={item.client.rfc || '—'}/><Info label="Teléfono" value={item.client.telefono || '—'}/><Info label="Correo" value={item.client.email || '—'}/><Info label="Domicilio" value={item.client.domicilio || '—'}/></div></section>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Ruta del proceso</h2><p className="mt-1 text-sm text-slate-500">Las etapas posteriores se consideran bloqueadas mientras exista una anterior pendiente.</p><div className="mt-5 space-y-3">{item.stages.map((stage, index) => { const blocked = item.stages.slice(0, index).some((value) => !['completado', 'cancelado'].includes(value.status)); const overdue = !!stage.deadline && stage.deadline < today && stage.status !== 'completado'; return <div key={stage.id} className={`rounded-xl border p-4 ${overdue ? 'border-red-200 bg-red-50/50' : stage.status === 'completado' ? 'border-emerald-200 bg-emerald-50/50' : 'bg-white'}`}><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{stage.order}</span><div><div className="flex items-center gap-2"><h3 className="font-bold">{stage.concept}</h3>{blocked && <LockKeyhole className="h-4 w-4 text-slate-400"/>}</div><p className="mt-1 text-sm text-slate-500">{stage.description || 'Sin descripción'}</p><p className={`mt-2 text-xs font-semibold ${overdue ? 'text-red-600' : 'text-slate-500'}`}><CalendarClock className="mr-1 inline h-3.5 w-3.5"/>{stage.deadline || 'Sin fecha límite'} · {money(stage.cost)} {stage.responsible ? `· ${stage.responsible}` : ''}</p></div></div><select disabled={saving === `stage-${index}`} value={stage.status} onChange={(event) => void updateStage(index, event.target.value as NotaryStageStatus)} className="h-10 rounded-lg border bg-white px-3 text-sm font-bold"><option value="pendiente">Pendiente</option><option value="en_proceso">En proceso</option><option value="detenido">Detenido</option><option value="completado">Completado</option><option value="cancelado">Cancelado</option></select></div></div>; })}</div></section>
    <div className="grid gap-6 xl:grid-cols-2"><Panel title="Registrar abono"><form onSubmit={addPayment} className="grid gap-3 sm:grid-cols-2"><Input required type="date" label="Fecha" value={payment.date} onChange={(e) => setPayment({ ...payment, date: e.target.value })}/><Input required type="number" min="0.01" step="0.01" label="Importe" value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: Number(e.target.value) })}/><label className="text-sm font-medium">Método<select className={`${inputClass} mt-1.5`} value={payment.method} onChange={(e) => setPayment({ ...payment, method: e.target.value })}><option>Transferencia</option><option>Depósito</option><option>Efectivo</option><option>Tarjeta</option><option>Cheque</option></select></label><Input label="Referencia" value={payment.reference} onChange={(e) => setPayment({ ...payment, reference: e.target.value })}/><button disabled={saving === 'payment'} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white sm:col-span-2">Registrar pago</button></form><div className="mt-5 divide-y border-t">{item.payments.map((value) => <div key={value.id} className="flex justify-between py-3 text-sm"><span>{value.date} · {value.method}<small className="block text-slate-400">{value.reference}</small></span><strong className="text-emerald-700">{money(value.amount)}</strong></div>)}</div></Panel>
      <Panel title="Generar orden de pago"><form onSubmit={createOrder} className="grid gap-3 sm:grid-cols-2"><Input required containerClassName="sm:col-span-2" label="Concepto" value={order.concept} onChange={(e) => setOrder({ ...order, concept: e.target.value })}/><Input required type="number" min="0.01" step="0.01" label="Importe" value={order.amount} onChange={(e) => setOrder({ ...order, amount: Number(e.target.value) })}/><Input type="date" label="Vence el" value={order.deadline} onChange={(e) => setOrder({ ...order, deadline: e.target.value })}/><button disabled={saving === 'order'} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white sm:col-span-2">Crear y descargar orden</button></form><div className="mt-5 divide-y border-t">{item.paymentOrders.map((value) => <button key={value.id} onClick={() => downloadPaymentOrder(item, { folio: value.folio, concepto: value.concept, monto: value.amount, fecha_limite: value.deadline })} className="flex w-full justify-between py-3 text-left text-sm hover:text-blue-600"><span><strong>{value.folio}</strong><small className="block text-slate-400">{value.concept}</small></span><span className="text-right"><strong>{money(value.amount)}</strong><Download className="ml-2 inline h-3.5 w-3.5"/></span></button>)}</div></Panel></div>
    <Panel title="Expediente documental del cliente"><form onSubmit={upload} className="grid gap-3 md:grid-cols-4"><label className="text-sm font-medium">Tipo<select className={`${inputClass} mt-1.5`} value={doc.type} onChange={(e) => setDoc({ ...doc, type: e.target.value })}><option>INE</option><option>CURP</option><option>CSF</option><option>Acta de nacimiento</option><option>Comprobante de domicilio</option><option>Escritura</option><option>Poder</option><option>Otro</option></select></label><Input type="date" label="Vencimiento" value={doc.expiresAt} onChange={(e) => setDoc({ ...doc, expiresAt: e.target.value })}/><label className="text-sm font-medium md:col-span-2">Archivo<input required type="file" accept=".pdf,.docx,image/png,image/jpeg,image/webp" onChange={(e) => setDoc({ ...doc, file: e.target.files?.[0] || null })} className={`${inputClass} mt-1.5 py-2`}/></label><button disabled={!doc.file || saving === 'document'} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white md:col-span-4"><Upload className="h-4 w-4"/>Subir documento</button></form><div className="mt-5 grid gap-3 md:grid-cols-2">{item.documents.map((value) => <button key={value.id} onClick={() => void downloadDoc(value.path, value.fileName)} className="flex items-center gap-3 rounded-xl border p-3 text-left hover:bg-slate-50"><span className="rounded-lg bg-blue-50 p-2 text-blue-600"><FileText className="h-4 w-4"/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{value.type}</strong><small className="block truncate text-slate-400">{value.fileName}{value.expiresAt ? ` · vence ${value.expiresAt}` : ''}</small></span><Download className="h-4 w-4 text-slate-400"/></button>)}</div></Panel>
  </div>;
}
function Summary({ label, value, icon: Icon, green, danger }: any) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className={`rounded-xl p-2.5 ${green ? 'bg-emerald-50 text-emerald-600' : danger ? 'bg-red-50 text-red-600' : 'bg-blue-50 text-blue-600'}`}><Icon className="h-5 w-5"/></span><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p></div></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-semibold text-slate-700">{value}</p></div>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-bold">{title}</h2>{children}</section>; }
