import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Download, FileCheck2, FileText, LockKeyhole, Send, Upload } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useAlerts } from '../components/AlertProvider';
import { downloadRadicationDraft, downloadSuccessionSearchRequest } from '../lib/notarySuccessionDocuments';
import { notaryProcessesApi } from '../services/notaryProcesses';
import { notarySuccessionsApi } from '../services/notarySuccessions';
import type { NotarySuccession, SuccessionSearch } from '../types/notaryProcess';

const today = new Date().toISOString().slice(0, 10); const field = 'h-10 w-full rounded-lg border bg-white px-3 text-sm outline-none focus:border-blue-500';
export function NotarySuccessionDetailPage() {
  const { id = '' } = useParams(); const [item, setItem] = useState<NotarySuccession | null>(null); const [saving, setSaving] = useState(''); const { notify } = useAlerts();
  const load = async () => { try { setItem(await notarySuccessionsApi.get(id)); } catch (error) { notify('error', 'No se pudo cargar la sucesión', error instanceof Error ? error.message : 'Intenta nuevamente.'); } };
  useEffect(() => { void load(); }, [id]);
  const ready = useMemo(() => !!item && item.requirements.every((requirement) => (!requirement.required || ['validado','no_aplica'].includes(requirement.status)) && (requirement.code !== 'CSF' || (!!requirement.expiresAt && requirement.expiresAt >= today))) && item.searches.every((search) => search.status === 'respondida'), [item]);
  const updateRequirement = async (requirementId: string, status: string, file?: File, expiresAt?: string) => { setSaving(requirementId); try { await notarySuccessionsApi.updateRequirement(requirementId, status, file, expiresAt); await load(); notify('success', 'Requisito actualizado'); } catch (error) { notify('error', 'No se pudo actualizar', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setSaving(''); } };
  const saveSearch = async (search: SuccessionSearch) => { setSaving(search.id); try { await notarySuccessionsApi.updateSearch(search.id, { status: search.status, requestDate: search.requestDate || '', requestFolio: search.requestFolio, responseDate: search.responseDate || '', responseFolio: search.responseFolio, result: search.result }); await load(); notify('success', 'Búsqueda actualizada'); } catch (error) { notify('error', 'No se pudo guardar', error instanceof Error ? error.message : 'Intenta nuevamente.'); } finally { setSaving(''); } };
  const patchSearch = (id: string, patch: Partial<SuccessionSearch>) => setItem((current) => current ? { ...current, searches: current.searches.map((search) => search.id === id ? { ...search, ...patch } : search) } : current);
  const patchRequirement = (id: string, expiresAt: string) => setItem((current) => current ? { ...current, requirements: current.requirements.map((requirement) => requirement.id === id ? { ...requirement, expiresAt } : requirement) } : current);
  if (!item) return <p className="py-12 text-center text-sm text-slate-500">Cargando sucesión...</p>;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Link to="/notaria/sucesiones" className="inline-flex items-center gap-2 text-sm font-bold text-blue-600"><ArrowLeft className="h-4 w-4"/>Sucesiones</Link><h1 className="mt-3 text-3xl font-bold">Sucesión de {item.deceased.name}</h1><p className="mt-2 text-sm text-slate-500"><span className="font-mono font-bold text-blue-600">{item.case.folio}</span> · Vía {item.route}</p></div><div className="flex flex-wrap gap-2"><Link to={`/notaria/expedientes/${item.caseId}`} className="inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><FileText className="h-4 w-4"/>Proceso y pagos</Link>{item.route === 'testamentaria' && <button disabled={!ready} onClick={() => void downloadRadicationDraft(item)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Download className="h-4 w-4"/>Proyecto de radicación</button>}</div></div>
    {!ready && <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><LockKeyhole className="h-5 w-5 shrink-0"/><div><p className="font-bold">Radicación bloqueada</p><p className="mt-1">Valida todos los requisitos obligatorios y registra la respuesta de ambas búsquedas.</p></div></div>}
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Requisitos de la vía {item.route}</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{item.requirements.map((requirement) => <div key={requirement.id} className="rounded-xl border p-4"><div className="flex items-start gap-3"><span className={`rounded-lg p-2 ${requirement.status === 'validado' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}><FileCheck2 className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="font-bold">{requirement.name}</p>{requirement.fileName && <p className="mt-1 truncate text-xs text-slate-400">{requirement.fileName}</p>}</div><select disabled={saving === requirement.id} value={requirement.status} onChange={(e) => void updateRequirement(requirement.id, e.target.value, undefined, requirement.expiresAt)} className="rounded-lg border px-2 py-1 text-xs font-bold"><option value="pendiente">Pendiente</option><option value="recibido">Recibido</option><option value="validado">Validado</option><option value="rechazado">Rechazado</option><option value="no_aplica">No aplica</option></select></div>{requirement.code === 'CSF' && <label className="mt-3 block text-xs font-medium text-slate-600">Vigente hasta<input type="date" value={requirement.expiresAt || ''} onChange={(e) => patchRequirement(requirement.id, e.target.value)} onBlur={() => void updateRequirement(requirement.id, requirement.status, undefined, requirement.expiresAt)} className={`${field} mt-1`}/>{requirement.expiresAt && requirement.expiresAt < today && <span className="mt-1 block font-bold text-red-600">Constancia vencida</span>}</label>}<label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed p-2 text-xs font-bold text-blue-600"><Upload className="h-3.5 w-3.5"/>Subir o reemplazar<input type="file" accept=".pdf,.docx,image/png,image/jpeg,image/webp" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) void updateRequirement(requirement.id, 'recibido', file, requirement.expiresAt); }}/></label></div>)}</div></section>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Búsquedas testamentarias obligatorias</h2><p className="mt-1 text-sm text-slate-500">Ambas se solicitan incluso en la vía intestamentaria para confirmar que no exista testamento.</p><div className="mt-5 grid gap-5 xl:grid-cols-2">{item.searches.map((search) => <div key={search.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-blue-600">{search.authority === 'registro_publico' ? 'Registro Público de la Propiedad' : 'Archivo General de Notarías'}</p><p className="mt-1 text-sm text-slate-500">Solicitud, seguimiento y respuesta</p></div><button onClick={() => downloadSuccessionSearchRequest(item, search.authority)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><Download className="h-3.5 w-3.5"/>Oficio</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Estatus<select value={search.status} onChange={(e) => patchSearch(search.id, { status: e.target.value as SuccessionSearch['status'] })} className={`${field} mt-1`}><option value="pendiente">Pendiente</option><option value="enviada">Enviada</option><option value="respondida">Respondida</option></select></label><label className="text-xs font-medium">Fecha solicitud<input type="date" value={search.requestDate || ''} onChange={(e) => patchSearch(search.id, { requestDate: e.target.value })} className={`${field} mt-1`}/></label><label className="text-xs font-medium">Folio solicitud<input value={search.requestFolio} onChange={(e) => patchSearch(search.id, { requestFolio: e.target.value })} className={`${field} mt-1`}/></label><label className="text-xs font-medium">Fecha respuesta<input type="date" value={search.responseDate || ''} onChange={(e) => patchSearch(search.id, { responseDate: e.target.value })} className={`${field} mt-1`}/></label><label className="text-xs font-medium">Folio respuesta<input value={search.responseFolio} onChange={(e) => patchSearch(search.id, { responseFolio: e.target.value })} className={`${field} mt-1`}/></label><label className="text-xs font-medium sm:col-span-2">Resultado<textarea rows={2} value={search.result} onChange={(e) => patchSearch(search.id, { result: e.target.value })} className={`${field} mt-1 h-auto py-2`}/></label></div><button disabled={saving === search.id} onClick={() => void saveSearch(search)} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white"><Send className="h-4 w-4"/>Guardar seguimiento</button></div>)}</div></section>
    <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Comparecientes y generales</h2><div className="mt-4 divide-y">{item.people.map((person, index) => <div key={`${person.client.curp}-${index}`} className="grid gap-2 py-4 md:grid-cols-[1fr_170px_170px]"><div><p className="font-bold">{notaryProcessesApi.clientName(person.client as any)}</p><p className="mt-1 text-xs text-slate-500">CURP {person.client.curp} · RFC {person.client.rfc || '—'} · {person.client.domicilio || 'Sin domicilio'}</p></div><div><p className="text-xs text-slate-400">Carácter</p><p className="text-sm font-bold capitalize">{person.role}</p></div><div><p className="text-xs text-slate-400">Parentesco</p><p className="text-sm font-bold">{person.relationship || '—'}</p></div></div>)}</div></section>
    {ready && <div className="flex gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="h-5 w-5"/><p><strong>Integración completa.</strong> Ya puede prepararse la radicación y continuar con la firma.</p></div>}
  </div>;
}
